export const REQUEST_EMPLOYEE = 'REQUEST_EMPLOYEE';
export const RECEIVE_EMPLOYEE = 'RECEIVE_EMPLOYEE';
export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT';
export const CHANGE_EMPLOYEE = 'CHANGE_EMPLOYEE';
export const CLEAR_ALL = 'CLEAR_ALL';